### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Donyme** [kasravnd/Rexy#1]
UPeT importer not found also https://github.com/kasramvd/UPeT ,**it's showing error:404 this is not the webpage you are looking for**

**Comment by kasravnd** [comment]
@Donyme I changed the name of UPeT module to Bagpipe but didn't change the imports. Thanks for noting that. I updated the repo. Please test now.

**Comment by Donyme** [comment]
Thanq! It worked!Also can you please update the readme/documentation with examples of how to run the recommender!It'll be GREAT

**Comment by kasravnd** [comment]
@Donyme You can use test files but I'll update the docs with more detailed explanations as soon as possible.
